### ISSUE TITLE
Time Block documentation and visual distinction

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#11]
At this point I am leaving this as a contribution request instead of a bug report because I think I'm misunderstanding what a time block is and how its supposed to be created.

I have observed that if I've set the startTime of more than one event to the same time frame that they will end up in the same general list together under the day view like so. 
I can see that the original name of the daily notes are showing and that the tasks are listed underneath. I am assuming that everything within this lighter grey area is a timeblock. Is this correct? 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/d4bc5dc2-c351-498d-aa43-1ca656329642)

Visually, I am confused as to whether this is a time block because up above in the unscheduled task area there are groups of tasks from within the same daily note displayed together in this same format. However, I know that in this area they are not yet timeblocks, because I can not move other unscheduled tasks in or out of them. It may be less confusing if the bar with a vertical line was not present in the unscheduled tasks area so that the tasks were instead grouped underneath the daily note itself. 

Another point of visual confusion is that there is lighter grey text underneath my note title that specifies the note title again. Upon analyzing a few notes, it appears that it may be trying to pick out headings that the tasks are grouped under but pulling the note title instead. 

Here is an example of my desired usecase for Time Ruler. I am coming from a method of using Full Calendar in order to create time blocks. My method involves creating the time block on my calendar first, then putting tasks in side of them. 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/bcafb7e2-e02d-4947-8b05-41a67aa7751a)

Although they do not have unique titles in this example, I often will give them unique titles based on what is inside of each time block which helps me to 'zoom out' and see my day as a big picture. 

In Time Ruler, since I am unable to specify a name for the time block, it's very difficult for me to see the relevant information from afar as to what needs to be done within that time period. This is especially because the note title that the task is from and the grey heading are visually distracting from the task title. I would find it helpful if these could be toggled on or off. 

One suggestion I have is to allow time block creation as either their own note within a directory (e.g. timeblock\) or as a section of the daily note. Then, a property could assign them to that particular timeblock and inherit the starttime and date from it. (e.g. if a TimeBlock "Declutter" is assigned on the 28th from 1PM to 3PM, and [timeBlock:: Declutter] is on a task, then Time Ruler will treat the scheduled time of the time block as its start time instead. This also helps prevent it from looking like everything during the time block is all due at the same time.) 

Similarly, if the timeblock is not yet scheduled, maybe they could show together under a the timeblock they belong in under the unscheduled task area? This way, all that needs to be done in order to schedule all of these grouped tasks is to drag the already created timeblock down into the schedule. 

These are merely suggestions from my own perspective, so please do not think I'm expecting you to implement any or even all of this. I just wanted to bring what felt natural for my workflow on to the table.

**Comment by joshuatazrein** [comment]
Thanks for this comprehensive report! These issues are very useful and I will improve documentation to sort this out. 

Some of these problems are bugs that I have fixed for the upcoming release:
- [x] Fixed bug where notes and headings get mistaken for daily notes and titled "Daily: ..." (this was an issue with the Regex used to parse daily note titles)

Others are user-experience improvements:
- [x] Tasks without a scheduled time now show up as a single block at the top of the day, instead of separated into previous times.

As far as the time-blocking question, my process is similar to yours and Time Ruler works well to accomodate this.
1. Create time blocks as scheduled tasks in a daily note, optionally with `[length:: #h#m]` set (or `[startTime:: ]` and `[endTime:: ]` for FullCalendar integrations)
2. Drag any tasks you want "in" this time block to be scheduled at the same time. The time block will add up all the lengths of tasks which are scheduled at the same time, which will be the full length of the block.
3. Drag the horizontal line around to reschedule the TimeBlock. All tasks will be rescheduled when dragging/dropping the block.

<img width="1308" alt="Screenshot 2023-07-28 at 9 07 31 AM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/84872947/91d14820-270f-49fb-a24e-97a2896ee278">

As far as future improvements, these are on my mind:
- [ ] Option to hide/show headings to reduce visual clutter
- [ ] Providing names for time blocks (perhaps by moving tasks with durations to the "name" field of a time block)

**Comment by technotherion** [comment]
> Thanks for this comprehensive report! These issues are very useful and I will improve documentation to sort this out.
> 
> Some of these problems are bugs that I have fixed for the upcoming release:
> 
>     * [x]  Fixed bug where notes and headings get mistaken for daily notes and titled "Daily: ..." (this was an issue with the Regex used to parse daily note titles)
> 
> 
> Others are user-experience improvements:
> 
>     * [x]  Tasks without a scheduled time now show up as a single block at the top of the day, instead of separated into previous times.
> 
> 
> As far as the time-blocking question, my process is similar to yours and Time Ruler works well to accomodate this.
> 
>     1. Create time blocks as scheduled tasks in a daily note, optionally with `[length:: #h#m]` set (or `[startTime:: ]` and `[endTime:: ]` for FullCalendar integrations)
> 
>     2. Drag any tasks you want "in" this time block to be scheduled at the same time. The time block will add up all the lengths of tasks which are scheduled at the same time, which will be the full length of the block.
> 
>     3. Drag the horizontal line around to reschedule the TimeBlock. All tasks will be rescheduled when dragging/dropping the block.
> 
> 
> <img alt="Screenshot 2023-07-28 at 9 07 31 AM" width="1308" src="https://user-images.githubusercontent.com/84872947/256859886-91d14820-270f-49fb-a24e-97a2896ee278.png">
> 
> As far as future improvements, these are on my mind:
> 
>     * [ ]  Option to hide/show headings to reduce visual clutter
> 
>     * [ ]  Providing names for time blocks (perhaps by moving tasks with durations to the "name" field of a time block)

Having all of the unassigned tasks and notes show up in the same block together is a huge improvement as far as being able to tell what is and isn't the day's timeline. 

I am going to try your timeblock  method described and see how that works for me. Thanks! I really love this plugin.

**Comment by joshuatazrein** [comment]
Awesome, I've added the additional features to the roadmap, so will close this issue for now.
