### ISSUE TITLE
can't figure out how to filter

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#37]
**Describe the bug**
I've looked at the dataview stuff and can't figure out what you want in the filter part of the settings.  An example of what to put to include a folder and its children, exclude a folder and its children and include 2 folders and exclude a third would be helpful

**Comment by joshuatazrein** [comment]
See this [link](https://blacksmithgu.github.io/obsidian-dataview/api/code-reference/#dvpagessource) for `dv.pages()` and this [link](https://blacksmithgu.github.io/obsidian-dataview/reference/sources/) for sources.

Include a folder and its children:
`"folder"`

Exclude a folder and its children:
`-"folder"`

Include two folders and exclude a third:
`"folder" or "folder2" and -"folder3"`

I'll update the docs.

**Comment by pcause** [comment]
thanks.  actually dv docs aren't great on this either.

**Comment by joshuatazrein** [comment]
Yeah it's confusing. Took me a while to figure out. I hope the examples in the docs will be more helpful.

**Comment by mossoc99** [comment]
Hello, thank you for this plugin which is one I am looking for since a long time 🙏 !

However, I cannot find a way to filter with this plugin.

I have looked through dataview doc like you mentionned here :
> See this [link](https://blacksmithgu.github.io/obsidian-dataview/api/code-reference/#dvpagessource) for `dv.pages()` and this [link](https://blacksmithgu.github.io/obsidian-dataview/reference/sources/) for sources.

I want that this plugin to only look for tasks that are in the folder Test:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/116178769/f357628f-7ca4-415b-b60d-b9b330b14869)
 
Here is Note 2: 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/116178769/f916f29f-6f8e-46ee-9a66-8d554a43cd76)

Here is the configuration for custom filter: `dv.pages('"Test"')`
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/116178769/147d25d6-8055-47be-8819-6c8327d90273)

Then I click on Open Time ruler in the left ribbon and here is the error I get:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/116178769/28996225-6789-482e-8d08-3cb905ae899b)

Could you please help me?

**Comment by j-palindrome** [comment]
Don't include `dv.pages()`, just include the query string.
