### ISSUE TITLE
All tasks from all past daily notes are displayed as today's tasks

### ISSUE THREAD

**Issue by revealed-dave** [joshuatazrein/obsidian-time-ruler#79]
**Describe the bug**

Hello there! I believe the screenshot fully describes the problem, but just in case: unfinished tasks from all past daily notes are displayed in the list of today's tasks. Which leads to a huge list of today's tasks and extremely slow plugin performance.

**To Reproduce**
1. Install Time Ruler
2. Open it
3. See list of all previous tasks from all past daily notes
4. Everything is slow as hell

**Expected behavior**
I mean, I'm not sure what I expect. But definitely not this list of recurring tasks from all the past notes.

As an option, don't display them.
At least separate them with headings.
But it's better not to display them.

**Screenshots**
<img width="1552" alt="Screenshot 2023-11-08 at 09 08 49" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/5278583/b0362863-4ae3-4ebd-98c9-88aaf3ee3845">

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Additional context**

**Comment by joshuatazrein** [comment]
This is a builtin behavior—TR doesn't show previous days, and any previous incomplete tasks show up in the current day. Any tasks in Daily Notes are scheduled for that day, so that's why all your daily tasks are showing up. 

The easiest thing to do would be to clean up by deleting the tasks or move the Daily notes themselves to an archive (or out of the Daily folder). There might be plugins for this...I use Archiver which could help.
