### ISSUE TITLE
This clean design is great... but to be able to drag into a timeline like Full Calendar would make it Next Level!

### ISSUE THREAD

**Issue by SolSynarchy** [joshuatazrein/obsidian-time-ruler#8]
To have all of the list of tasks from various notes on the sidebar and Drag and Drop into Full Calendar would be Ideal.
Could you guys join forces or is there a way to emulate the Full Calendar in your app? 
Here they are side by side... they look great but no drag drop functionality between them. 

<img width="1565" alt="Screenshot 2023-07-24 at 8 36 13 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/140476728/a1b16417-8167-4463-9b87-29f20d07f121">

**Comment by joshuatazrein** [comment]
This is a great idea. Currently the drag-and-drop library Time Ruler uses would have to be supplemented by something else in order to be compatible, but this would certainly be interesting! 

Currently the best way to do it is to switch from daily view to hourly view in Time Ruler (the calendar button) and drag tasks to the specific time, which should update in Full Calendar if the data format is working appropriately (let me know if this is glitchy and I can fix).

You can also drag the Time Ruler icon to the main split to view an expanded 4-day view. Once tasks update, Full Calendar should sync the data to its own UI.

**Comment by joshuatazrein** [comment]
I'm closing this issue as the most basic thing would be to enable FullCalendar to automatically refresh events when Obsidian data changes. I would ask the developers there to update the plugin's refresh settings to better integrate with Time Ruler.
